image: registry.gitlab.com/brainail/EverboxingLingo

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle assembleDebug
  artifacts:
    paths:
    - mobile/build/outputs/

unitTests:
  stage: test
  script:
    - gradle junitPlatformTest # :domain
    - gradle junitPlatformTestDebug # :mobile and :data (task from junit5 android plugin)